export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_FRIEND = "CREATE_FRIEND"; // C
export const GET_FRIEND = "GET_FRIEND";       // R
export const UPDATE_FRIEND = "UPDATE_FRIEND"; // U
export const DELETE_FRIEND = "DELETE_FRIEND"; // D

export const ADDING_TRIP = "ADDING_TRIP";
export const ADDED_TRIP = "ADDED_TRIP";
export const GET_TRIP = "GET_TRIP";
export const UPDATING_TRIP = "UPDATING_TRIP";
export const UPDATED_TRIP = "UPDATED_TRIP";
export const DELETING_TRIP = "DELETING_TRIP";
export const DELETED_TRIP = "DELETED_TRIP";
export const GET_ALL_TRIPS = "GET_ALL_TRIPS";

export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";

export const CREATE_PARKING_LOT = "CREATE_PARKING_LOT";
export const GET_PARKING_LOT = "GET_PARKING_LOT";
export const UPDATE_PARKING_LOT = "UPDATE_PARKING_LOT";
export const DELETE_PARKING_LOT = "DELETE_PARKING_LOT";
export const GET_ALL_PARKING_LOTS = "GET_ALL_PARKING_LOTS";

export const ADDING_SHOPPING_LIST = "ADDING_SHOPPING_LIST";
export const ADDED_SHOPPING_LIST = "ADDED_SHOPPING_LIST";
export const GET_SHOPPING_LIST = "GET_SHOPPING_LIST";
export const UPDATING_SHOPPING_LIST = "UPDATING_SHOPPING_LIST";
export const UPDATED_SHOPPING_LIST = "UPDATED_SHOPPING_LIST";
export const DELETING_SHOPPING_LIST = "DELETING_SHOPPING_LIST";
export const DELETED_SHOPPING_LIST = "DELTED_SHOPPING_LIST"
export const GET_ALL_SHOPPING_LISTS = "GET_ALL_GET_ALL_SHOPPING_LISTS";

export const CREATE_FLIGHT = "CREATE_FLIGHT"
export const GET_FLIGHT = "GET_FLIGHT";
export const UPDATE_FLIGHT = "UPDATE_FLIGHT"
export const DELETE_FLIGHT = "DELETE_FLIGHT"
export const GET_ALL_FLIGHTS = "GET_ALL_FLIGHTS"
